services:
  fastapi:
    env_file:
      - .env.prod
    build:
      context: .
      target: ${STAGE}
      dockerfile: prod.Dockerfile
      args:
        - APP_VERSION=${APP_VERSION}
        - PORT_LOCAL=${PORT_LOCAL}
        - PORT_REMOTE=${PORT_REMOTE}
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: ${DOCKER_FASTAPI_NAME}
    restart: always
    environment:
      - PIPELINE_VERSION=${PIPELINE_VERSION}
      - PORT_LOCAL=${PORT_LOCAL}
      - PORT_REMOTE=${PORT_REMOTE}
      - PYTHONPATH=/app
    ports:
      - '${PORT_LOCAL}:${PORT_REMOTE}' 
    networks:
      - ${APP_NETWORK_NAME}

networks:
  renovacion_prestamo-net:
    name: ${APP_NETWORK_NAME}
    driver: bridge